remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Sophie Ly Biography
description: Welcome to a page all about me because I'm amazing!
