remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: Sophie Ly Biography
description: Sophie is a 17-year-old high school senior who loves to sing, play pickleball for fun, study at cafes, go to the gym, and serve for Drama Club as Secretary and for Key Club!
